services:
  partner-front:
    build:
      context: ${CONTEXT_DIR}
      dockerfile: ./docker/local/Dockerfile
    container_name: local-partner-front
    ports:
      - "${PARTNER_FE_PORT}:3000"
    env_file:
      - .env.local
    volumes:
      - ${CONTEXT_DIR}:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - partner-network

networks:
  partner-network:
    name: partner-network
